const quranData = [
    { id: 1, name: "Al-Fatiha", trans: "The Opening", verses: [{ ar: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", ur: "Allah ke naam se shuru jo nihayat meharban reham wala hai." }, { ar: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", ur: "Sab tareefen Allah ke liye hain jo tamam jahanon ka rab hai." }] },
    { id: 2, name: "Al-Baqarah", trans: "The Cow", verses: [{ ar: "الٓمٓ", ur: "Alif-Laam-Meem" }, { ar: "ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِّلْمُتَّقِينَ", ur: "Ye wo kitab hai jis mein koi shak nahi, hidayat hai darne walon ke liye." }] },
    { id: 3, name: "Aal-E-Imran", trans: "Family of Imran", verses: [{ ar: "الٓمٓ", ur: "Alif-Laam-Meem" }] },
    { id: 4, name: "An-Nisa", trans: "The Women", verses: [{ ar: "يَا أَيُّهَا النَّاسُ اتَّقُوا رَبَّكُمُ", ur: "Ay logon! Apne rab se daro." }] },
    { id: 5, name: "Al-Ma'idah", trans: "The Table Spread", verses: [{ ar: "يَا أَيُّهَا الَّذِينَ آمَنُوا أَوْفُوا بِالْعُقُودِ", ur: "Ay iman walon! Apne waadon ko poora karo." }] },
    { id: 6, name: "Al-An'am", trans: "The Cattle", verses: [{ ar: "الْحَمْدُ لِلَّهِ الَّذِي خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ", ur: "Tamam tareefen us Allah ke liye hain jisne aasman aur zameen banaye." }] },
    { id: 7, name: "Al-A'raf", trans: "The Heights", verses: [{ ar: "الٓمٓصٓ", ur: "Alif-Laam-Meem-Saad" }] },
    { id: 8, name: "Al-Anfal", trans: "The Spoils of War", verses: [{ ar: "يَسْأَلُونَكَ عَنِ الْأَنفَالِ", ur: "Ye aapse ghanimat ke baare mein puchte hain." }] },
    { id: 9, name: "At-Tawbah", trans: "The Repentance", verses: [{ ar: "بَرَاءَةٌ مِّنَ اللَّهِ وَرَسُولِهِ", ur: "Allah aur uske Rasool ki taraf se elaan-e-bara'at hai." }] },
    { id: 10, name: "Yunus", trans: "Jonah", verses: [{ ar: "الر ۚ تِلْكَ آيَاتُ الْكِتَابِ الْحَكِيمِ", ur: "Alif-Laam-Ra, ye hikmat wali kitab ki ayat hain." }] },
    { id: 11, name: "Hud", trans: "Hud", verses: [{ ar: "الر ۚ كِتَابٌ أُحْكِمَتْ آيَاتُهُ", ur: "Ye wo kitab hai jis ki ayat pukhta ki gayi hain." }] },
    { id: 12, name: "Yusuf", trans: "Joseph", verses: [{ ar: "الر ۚ تِلْكَ آيَاتُ الْكِتَابِ الْمُبِينِ", ur: "Humne ise wazeh kitab ki ayat banaya." }] },
    { id: 13, name: "Ar-Ra'd", trans: "The Thunder", verses: [{ ar: "المر ۚ تِلْكَ آيَاتُ الْكِتَابِ", ur: "Alif-Laam-Meem-Ra, ye kitab ki ayat hain." }] },
    { id: 14, name: "Ibrahim", trans: "Abraham", verses: [{ ar: "الر ۚ كِتَابٌ أَنزَلْنَاهُ إِلَيْكَ", ur: "Ye wo kitab hai jo humne aapki taraf nazil ki." }] },
    { id: 15, name: "Al-Hijr", trans: "The Rocky Tract", verses: [{ ar: "الر ۚ تِلْكَ آيَاتُ الْكِتَابِ وَقُرْآنٍ مُّبِينٍ", ur: "Ye kitab aur wazeh Quran ki ayat hain." }] },
    { id: 16, name: "An-Nahl", trans: "The Bee", verses: [{ ar: "أَتَىٰ أَمْرُ اللَّهِ فَلَا تَسْتَعْجِلُوهُ", ur: "Allah ka hukum aa pahoncha, ab jaldi na karo." }] },
    { id: 17, name: "Al-Isra", trans: "The Night Journey", verses: [{ ar: "سُبْحَانَ الَّذِي أَسْرَىٰ بِعَبْدِهِ", ur: "Paak hai wo zaat jo apne bande ko raat mein le gayi." }] },
    { id: 18, name: "Al-Kahf", trans: "The Cave", verses: [{ ar: "الْحَمْدُ لِلَّهِ الَّذِي أَنزَلَ عَلَىٰ عَبْدِهِ الْكِتَابَ", ur: "Shukr hai Allah ka jisne apne bande par kitab utari." }] },
    { id: 19, name: "Maryam", trans: "Mary", verses: [{ ar: "كَهيَعٓصٓ", ur: "Kaaf-Ha-Ya-Ain-Saad" }] },
    { id: 20, name: "Ta-Ha", trans: "Ta-Ha", verses: [{ ar: "طه", ur: "Ta-Ha" }] },
    { id: 21, name: "Al-Anbiya", trans: "The Prophets", verses: [{ ar: "اقْتَرَبَ لِلنَّاسِ حِسَابُهُمْ", ur: "Logon ke hisab ka waqt qareeb aa gaya." }] },
    { id: 22, name: "Al-Hajj", trans: "The Pilgrimage", verses: [{ ar: "يَا أَيُّهَا النَّاسُ اتَّقُوا رَبَّكُمُ", ur: "Ay logon! Apne rab se daro." }] },
    { id: 23, name: "Al-Mu'minun", trans: "The Believers", verses: [{ ar: "قَدْ أَفْلَحَ الْمُؤْمِنُونَ", ur: "Yaqeenan iman wale kamyab ho gaye." }] },
    { id: 24, name: "An-Nur", trans: "The Light", verses: [{ ar: "سُورَةٌ أَنزَلْنَاهَا وَفَرَضْنَاهَا", ur: "Ye ek surah hai jo humne nazil ki aur ise farz kiya." }] },
    { id: 25, name: "Al-Furqan", trans: "The Criterion", verses: [{ ar: "تَبَارَكَ الَّذِي نَزَّلَ الْفُرْقَانَ", ur: "Badi barkat wala hai wo jisne Furqan nazil kiya." }] },
    { id: 26, name: "Ash-Shu'ara", trans: "The Poets", verses: [{ ar: "طسٓمٓ", ur: "Ta-Seen-Meem" }] },
    { id: 27, name: "An-Naml", trans: "The Ant", verses: [{ ar: "طسٓ ۚ تِلْكَ آيَاتُ الْقُرْآنِ", ur: "Ta-Seen, ye Quran ki ayat hain." }] },
    { id: 28, name: "Al-Qasas", trans: "The Stories", verses: [{ ar: "طسٓمٓ", ur: "Ta-Seen-Meem" }] },
    { id: 29, name: "Al-Ankabut", trans: "The Spider", verses: [{ ar: "الٓمٓ", ur: "Alif-Laam-Meem" }] },
    { id: 30, name: "Ar-Rum", trans: "The Romans", verses: [{ ar: "الٓمٓ", ur: "Alif-Laam-Meem" }] },
    { id: 31, name: "Luqman", trans: "Luqman", verses: [{ ar: "الٓمٓ", ur: "Alif-Laam-Meem" }] },
    { id: 32, name: "As-Sajdah", trans: "The Prostration", verses: [{ ar: "الٓمٓ", ur: "Alif-Laam-Meem" }] },
    { id: 33, name: "Al-Ahzab", trans: "The Combined Forces", verses: [{ ar: "يَا أَيُّهَا النَّبِيُّ اتَّقِ اللَّهَ", ur: "Ay Nabi! Allah se daro." }] },
    { id: 34, name: "Saba", trans: "Sheba", verses: [{ ar: "الْحَمْدُ لِلَّهِ الَّذِي لَهُ مَا فِي السَّمَاوَاتِ", ur: "Shukr hai Allah ka jis ke liye jo kuch aasmano mein hai." }] },
    { id: 35, name: "Fatir", trans: "Originator", verses: [{ ar: "الْحَمْدُ لِلَّهِ فَاطِرِ السَّمَاوَاتِ", ur: "Shukr hai Allah ka jo aasmano ko banane wala hai." }] },
    { id: 36, name: "Ya-Sin", trans: "Ya Sin", verses: [{ ar: "يس", ur: "Ya-Seen" }] },
    { id: 37, name: "As-Saffat", trans: "Those who set the Ranks", verses: [{ ar: "وَالصَّافَّاتِ صَفًّا", ur: "Qasam hai saf bandhne walon ki." }] },
    { id: 38, name: "Sad", trans: "The Letter Saad", verses: [{ ar: "ص ۚ وَالْقُرْآنِ ذِي الذِّكْرِ", ur: "Saad, qasam hai naseehat wale Quran ki." }] },
    { id: 39, name: "Az-Zumar", trans: "The Troops", verses: [{ ar: "تَنزِيلُ الْكِتَابِ مِنَ اللَّهِ", ur: "Is kitab ka nazil hona Allah ki taraf se hai." }] },
    { id: 40, name: "Ghafir", trans: "The Forgiver", verses: [{ ar: "حم", ur: "Ha-Meem" }] },
    { id: 41, name: "Fussilat", trans: "Explained in Detail", verses: [{ ar: "حم", ur: "Ha-Meem" }] },
    { id: 42, name: "Ash-Shura", trans: "The Consultation", verses: [{ ar: "حم", ur: "Ha-Meem" }] },
    { id: 43, name: "Az-Zukhruf", trans: "The Ornaments of Gold", verses: [{ ar: "حم", ur: "Ha-Meem" }] },
    { id: 44, name: "Ad-Dukhan", trans: "The Smoke", verses: [{ ar: "حم", ur: "Ha-Meem" }] },
    { id: 45, name: "Al-Jathiyah", trans: "The Crouching", verses: [{ ar: "حم", ur: "Ha-Meem" }] },
    { id: 46, name: "Al-Ahqaf", trans: "The Wind-Curved Sandhills", verses: [{ ar: "حم", ur: "Ha-Meem" }] },
    { id: 47, name: "Muhammad", trans: "Muhammad", verses: [{ ar: "الَّذِينَ كَفَرُوا وَصَدُّوا عَن سَبِيلِ اللَّهِ", ur: "Wo log jinhone kufr kiya aur Allah ki raah se roka." }] },
    { id: 48, name: "Al-Fath", trans: "The Victory", verses: [{ ar: "إِنَّا فَتَحْنَا لَكَ فَتْحًا مُّبِينًا", ur: "Beshak humne aapko wazeh fateh di." }] },
    { id: 49, name: "Al-Hujurat", trans: "The Dwellings", verses: [{ ar: "يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تُقَدِّمُوا بَيْنَ يَدَيِ اللَّهِ", ur: "Ay iman walon! Allah aur Rasool se aage na badho." }] },
    { id: 50, name: "Qaf", trans: "The Letter Qaf", verses: [{ ar: "ق ۚ وَالْقُرْآنِ الْمَجِيدِ", ur: "Qaf, qasam hai majeed Quran ki." }] }
];
